export const FIREWORKS_TOTAL_IN_CART_UPDATED = 'FIREWORKS_TOTAL_IN_CART_UPDATED';
export const BONUS_REWARD_UPDATED = 'BONUS_REWARD_UPDATED';
export const SHOPIFY_CART_UPDATE = 'SHOPIFY_CART_UPDATE';
export const UPDATE = 'UPDATE';
